### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dacalation** [kanu/django-update-returning#2]
Hi, thanks for open sourcing this!  What license is it available under?

**Comment by kanu** [comment]
Hi,
I havn't thought about restricting this in any way. If you like it, take it. 
I will seach for a propper license and add it.

**Comment by dacalation** [comment]
Hi, thank you for that.  Unfortunately, the law in most countries says that by default the copyright belongs to you and the code can't be used by others, even if it's on Github :).  Thanks again for the code, and let me know when you've found a license.  This information may help: http://opensource.org/licenses

**Comment by kanu** [comment]
Hi there,
The code is now under unlicense. Hope it is of any use.
